repos:
  - repo: https://github.com/psf/black
    rev: "24.10.0" # Use the sha / tag you want to point at
    hooks:
      - id: black

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.13.2
  #   hooks:
  #     - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-docstrings
        # exclude: ^src/blib2to3/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    # docs https://pre-commit.com/hooks.html
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
        exclude: "^poetry\\.lock$"
      - id: check-yaml
      - id: debug-statements
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-toml

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
